api:
  uri: https://mocki.io/v1/e6f202bd-0f7e-48ff-a87e-2d3cfb0ae7a9
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true